# Используем официальный Node.js образ
FROM node:20-alpine

# Рабочая директория
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем только production зависимости
RUN npm ci --only=production

RUN npm install 

# Копируем исходный код
COPY . .

# Открываем порт (по умолчанию 5000)
EXPOSE 5000

# Запуск приложения
CMD ["node", "server.js"] 